name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - uses: christianvuerings/add-labels@v1
        with:
          labels: approved
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
